#!/usr/bin/env bash

#---------------------------------
#  Copyright 2025-2026 NXP
#---------------------------------

set -e

VENV_PATH="/usr/share/smart-device-gateway/venv"

. "$VENV_PATH/bin/activate"
edge-voice "$@"